### PR TITLE
Add Taylor Swift meme to L35-slides-Rust.pdf

### PR DESCRIPTION
**Pull request by kennethsinder**
Add a [Fearless Concurrency album art meme from Twitter](https://twitter.com/ManishEarth/status/1025423234576076800) as an extra slide in `L35-slides-Rust.pdf`.

You can check out the PDF in the PR by displaying the rich diff, but here's what the new slide looks like: 
image

This is, of course, pedagogically a very important improvement.

### CODE REVIEW

**Comment by jzarnett** [comment]
Is the Dune reference too obscure?!

**Comment by kennethsinder** [comment]
(I'm personally not familiar with the Dune reference, but) By keeping the Dune reference on the previous slide, we provide optionality so students who may not relate to that one can enjoy this one :)

**Comment by jzarnett** [comment]
Dune's worth reading, or if you prefer, watching the miniseries/movie. It has Patrick Stewart before he was Captain Picard! But anyway, it's a mantra that Paul learns. Here's a way to learn it that is... topical.

image

**Comment by patricklam** [comment]
+1!

**Pull request merged**
